from prometheus_client import Counter, Histogram

# === HTTP / business ============================================================

TRANSCRIPTIONS_TOTAL = Counter(
    "transcriptions_total",
    "Total transcriptions processed",
    ["status", "request_type"],
)

TRANSCRIPTION_CONFIDENCE = Histogram(
    "transcription_confidence",
    "Distribution of confidence scores returned by the model",
    buckets=[0.5, 0.7, 0.8, 0.9, 0.95, 0.99, 1.0],
)

TRANSCRIBED_TEXT_LENGTH = Histogram(
    "transcribed_text_length_chars",
    "Length of transcribed HTML content in characters",
    buckets=[100, 250, 500, 1000, 2500, 5000, 10000],
)

# === OpenAI Vision ==============================================================

OPENAI_CALL_DURATION = Histogram(
    "openai_call_duration_seconds",
    "Duration of OpenAI Vision API calls",
    ["model", "status"],
    buckets=[0.5, 1, 2, 5, 10, 20, 30, 60],
)

OPENAI_TOKENS_INPUT = Counter(
    "openai_tokens_input_total",
    "Total input tokens consumed by OpenAI Vision",
    ["model"],
)

OPENAI_TOKENS_OUTPUT = Counter(
    "openai_tokens_output_total",
    "Total output tokens generated by OpenAI Vision",
    ["model"],
)

# === Database ===================================================================

DB_OPERATION_DURATION = Histogram(
    "db_operation_duration_seconds",
    "Duration of database operations",
    ["operation"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
)

DB_WRITE_ERRORS = Counter(
    "db_write_errors_total",
    "Database write failures (transcription returned to user despite DB failure)",
    ["operation"],
)